# Generated by Django 4.2.20 on 2025-05-31 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_remove_post_image_replycomment_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
