# Generated by Django 6.0.3 on 2026-04-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_delete_replycomment'),
        ('social', '0013_alter_comment_options_remove_comment_level_and_more'),
    ]

    operations = [
    ]
