# Generated by Django 4.2.20 on 2026-01-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_post_shared_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'FeMale'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
